const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const clientDist = path.join(root, "client", "dist");
const bundlePath = path.join(root, "server", "src", "generated", "clientBundle.ts");

const ensureDir = (dir) => fs.mkdirSync(dir, { recursive: true });

const collectFiles = (dir, prefix = "") => {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const results = [];
  for (const entry of entries) {
    const absPath = path.join(dir, entry.name);
    const relPath = path.join(prefix, entry.name).replace(/\\/g, "/");
    if (entry.isDirectory()) {
      results.push(...collectFiles(absPath, relPath));
    } else if (entry.isFile()) {
      results.push({ absPath, relPath });
    }
  }
  return results;
};

if (!fs.existsSync(clientDist)) {
  console.error("Missing client/dist. Run npm --workspace client run build first.");
  process.exit(1);
}

const files = collectFiles(clientDist);
const entries = files.map((file) => {
  const data = fs.readFileSync(file.absPath);
  return {
    path: file.relPath,
    data: data.toString("base64"),
  };
});

const timestamp = new Date().toISOString();
const content =
  `// Auto-generated by scripts/prepare-pkg.js\n` +
  `export const clientBundleTimestamp = ${JSON.stringify(timestamp)};\n` +
  `export const clientBundle = ${JSON.stringify(entries)} as Array<{ path: string; data: string }>;\n`;

ensureDir(path.dirname(bundlePath));
fs.writeFileSync(bundlePath, content, "utf8");
console.log(`Prepared client bundle: ${bundlePath}`);
